local BLOCKS = require(game.ReplicatedStorage.LocalModules.BlocksID)
		local classicInventory = {
			BLOCKS.BLOCK_STONE, BLOCKS.BLOCK_COBBLE, BLOCKS.BLOCK_BRICK, BLOCKS.BLOCK_DIRT, BLOCKS.BLOCK_WOOD, BLOCKS.BLOCK_LOG, BLOCKS.BLOCK_LEAVES, BLOCKS.BLOCK_GLASS, BLOCKS.BLOCK_SLAB,
			BLOCKS.BLOCK_MOSSY_ROCKS, BLOCKS.BLOCK_SAPLING, BLOCKS.BLOCK_DANDELION, BLOCKS.BLOCK_ROSE, BLOCKS.BLOCK_BROWN_SHROOM, BLOCKS.BLOCK_RED_SHROOM, BLOCKS.BLOCK_SAND, BLOCKS.BLOCK_GRAVEL, BLOCKS.BLOCK_SPONGE,
			BLOCKS.BLOCK_RED, BLOCKS.BLOCK_ORANGE, BLOCKS.BLOCK_YELLOW, BLOCKS.BLOCK_LIME, BLOCKS.BLOCK_GREEN, BLOCKS.BLOCK_TEAL, BLOCKS.BLOCK_AQUA, BLOCKS.BLOCK_CYAN, BLOCKS.BLOCK_BLUE,
			BLOCKS.BLOCK_INDIGO, BLOCKS.BLOCK_VIOLET, BLOCKS.BLOCK_MAGENTA, BLOCKS.BLOCK_PINK, BLOCKS.BLOCK_BLACK, BLOCKS.BLOCK_GRAY, BLOCKS.BLOCK_WHITE, BLOCKS.BLOCK_COAL_ORE, BLOCKS.BLOCK_IRON_ORE,
			BLOCKS.BLOCK_GOLD_ORE, BLOCKS.BLOCK_IRON, BLOCKS.BLOCK_GOLD, BLOCKS.BLOCK_BOOKSHELF, BLOCKS.BLOCK_TNT, BLOCKS.BLOCK_OBSIDIAN, BLOCKS.FLOWING_WATER, BLOCKS.FLOWING_LAVA
		}
		
game.ReplicatedStorage.Remote.GetAllowedBlocks.OnServerInvoke = function()
	return classicInventory
end

return true